import {
  Bot,
  Search,
  Code,
  Calendar,
  Mail,
  Database,
  Globe,
  FileText,
  Puzzle,
  Zap,
  Shield,
  MessageSquare,
  Lightbulb,
  TrendingUp,
  Briefcase,
  MapPin,
  Store,
} from 'lucide-react'
import {
  JiraIcon,
  SlackIcon,
  GitHubIcon,
  NotionIcon,
  WhatsAppIcon,
  TrelloIcon,
  XIcon,
  DiscordIcon,
  LinkedInIcon,
  RedditIcon,
  GoogleMapsIcon,
  TelegramIcon,
  GoogleSheetsIcon,
  YouTubeIcon,
  SpotifyIcon,
  AirtableIcon,
  FigmaIcon,
  InstagramIcon,
  TikTokIcon,
  GoogleCalendarIcon,
  GmailIcon,
  AmazonIcon,
  HackerNewsIcon,
  FacebookIcon,
  IndeedIcon,
  GoogleFlightsIcon,
  BookingIcon,
  AirbnbIcon,
  PinterestIcon,
  EbayIcon,
  ShopifyIcon,
  CoinMarketCapIcon,
  GoogleNewsIcon,
  GlassdoorIcon,
  TripAdvisorIcon,
  ThreadsIcon,
  GoogleScholarIcon,
  EtsyIcon,
  YahooFinanceIcon,
  ZillowIcon,
  WikipediaIcon,
  WalmartIcon,
  TwitchIcon,
  IMDbIcon,
  YelpIcon,
  AliExpressIcon,
  QuoraIcon,
  BlueskyIcon,
  MediumIcon,
  SubstackIcon,
  StackOverflowIcon,
  ExpediaIcon,
  SoundCloudIcon,
  RottenTomatoesIcon,
  CanvaIcon,
  ProductHuntIcon,
  CourseraIcon,
  UdemyIcon,
  KaggleIcon,
  HuggingFaceIcon,
  StravaIcon,
  GoodreadsIcon,
  CoinbaseIcon,
  DiscogsIcon,
  LetterboxdIcon,
  TodoistIcon,
  CraigslistIcon,
  MyFitnessPalIcon,
  DuolingoIcon,
  TinderIcon,
  StockXIcon,
  ArxivIcon,
  WaybackIcon,
  BandcampIcon,
  LastfmIcon,
  OpenSeaIcon,
  UntappdIcon,
  TransfermarktIcon,
  VivinoIcon,
  ESPNIcon,
} from '~/components/ui/platform-icons'

/** Canonical icon mapping shared across agent UI surfaces */
export const agentIconMap: Record<string, typeof Bot> = {
  'bot': Bot,
  'search': Search,
  'code': Code,
  'calendar': Calendar,
  'mail': Mail,
  'database': Database,
  'globe': Globe,
  'file-text': FileText,
  'puzzle': Puzzle,
  'zap': Zap,
  'shield': Shield,
  'message-square': MessageSquare,
  'lightbulb': Lightbulb,
  'trending-up': TrendingUp,
  'briefcase': Briefcase,
  'map-pin': MapPin,
  'twitter': XIcon,
  'jira': JiraIcon,
  'slack': SlackIcon,
  'github': GitHubIcon,
  'notion': NotionIcon,
  'whatsapp': WhatsAppIcon,
  'trello': TrelloIcon,
  'discord': DiscordIcon,
  'linkedin': LinkedInIcon,
  'reddit': RedditIcon,
  'google-maps': GoogleMapsIcon,
  'telegram': TelegramIcon,
  'google-sheets': GoogleSheetsIcon,
  'youtube': YouTubeIcon,
  'spotify': SpotifyIcon,
  'airtable': AirtableIcon,
  'figma': FigmaIcon,
  'instagram': InstagramIcon,
  'tiktok': TikTokIcon,
  'google-calendar': GoogleCalendarIcon,
  'gmail': GmailIcon,
  'amazon': AmazonIcon,
  'hackernews': HackerNewsIcon,
  'facebook': FacebookIcon,
  'indeed': IndeedIcon,
  'google-flights': GoogleFlightsIcon,
  'booking': BookingIcon,
  'airbnb': AirbnbIcon,
  'pinterest': PinterestIcon,
  'ebay': EbayIcon,
  'shopify': ShopifyIcon,
  'coinmarketcap': CoinMarketCapIcon,
  'google-news': GoogleNewsIcon,
  'glassdoor': GlassdoorIcon,
  'tripadvisor': TripAdvisorIcon,
  'threads': ThreadsIcon,
  'google-scholar': GoogleScholarIcon,
  'etsy': EtsyIcon,
  'yahoo-finance': YahooFinanceIcon,
  'zillow': ZillowIcon,
  'wikipedia': WikipediaIcon,
  'walmart': WalmartIcon,
  'twitch': TwitchIcon,
  'imdb': IMDbIcon,
  'yelp': YelpIcon,
  'aliexpress': AliExpressIcon,
  'quora': QuoraIcon,
  'bluesky': BlueskyIcon,
  'medium': MediumIcon,
  'substack': SubstackIcon,
  'stackoverflow': StackOverflowIcon,
  'expedia': ExpediaIcon,
  'soundcloud': SoundCloudIcon,
  'rottentomatoes': RottenTomatoesIcon,
  'canva': CanvaIcon,
  'producthunt': ProductHuntIcon,
  'coursera': CourseraIcon,
  'udemy': UdemyIcon,
  'kaggle': KaggleIcon,
  'huggingface': HuggingFaceIcon,
  'strava': StravaIcon,
  'goodreads': GoodreadsIcon,
  'coinbase': CoinbaseIcon,
  'discogs': DiscogsIcon,
  'letterboxd': LetterboxdIcon,
  'todoist': TodoistIcon,
  'craigslist': CraigslistIcon,
  'myfitnesspal': MyFitnessPalIcon,
  'duolingo': DuolingoIcon,
  'tinder': TinderIcon,
  'stockx': StockXIcon,
  'arxiv': ArxivIcon,
  'wayback': WaybackIcon,
  'bandcamp': BandcampIcon,
  'lastfm': LastfmIcon,
  'opensea': OpenSeaIcon,
  'untappd': UntappdIcon,
  'transfermarkt': TransfermarktIcon,
  'vivino': VivinoIcon,
  'espn': ESPNIcon,
  'store': Store,
}

/** Look up an icon component by its ID. Returns null if not found. */
export function getAgentIcon(iconId: string) {
  return agentIconMap[iconId] || null
}

/** Render an agent icon - either a Lucide/platform icon component or an emoji */
export function AgentIconDisplay({ iconId, className, emojiClassName }: {
  iconId: string
  className?: string
  emojiClassName?: string
}) {
  const Icon = agentIconMap[iconId]
  if (Icon) {
    return <Icon className={className} />
  }
  if (iconId && iconId.length > 0) {
    return <span className={emojiClassName || className}>{iconId}</span>
  }
  return <Bot className={className} />
}
