/**
 * Auto-discovery of agent definitions.
 * Scans packages/agents for subdirs with definition.ts and generates src/generated.ts
 */
import { readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const ROOT = join(__dirname, '..')
const AGENTS_DIR = ROOT

const dirs = readdirSync(AGENTS_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !['shared', 'scripts', 'src'].includes(e.name))
  .filter((e) => existsSync(join(AGENTS_DIR, e.name, 'definition.ts')))
  .map((e) => e.name)
  .sort((a, b) => {
    if (a === 'general') return -1
    if (b === 'general') return 1
    return a.localeCompare(b)
  })

const imports = dirs
  .map((d) => {
    const varName = d.replace(/-/g, '_')
    return `import { definition as ${varName} } from '../${d}/definition.js'`
  })
  .join('\n')

const arr = dirs.map((d) => d.replace(/-/g, '_')).join(', ')

const content = `/** Auto-generated by scripts/discover-agents.ts - do not edit */\n\n${imports}\n\nexport const BUILTIN_AGENT_DEFINITIONS = [${arr}]\n\nexport const IMPLICIT_AGENT_SERVERS: Record<string, string[]> = Object.fromEntries(\n  BUILTIN_AGENT_DEFINITIONS.map((a) => [a.id, a.implicitMCPIds])\n)\n`

const outDir = join(ROOT, 'src')
mkdirSync(outDir, { recursive: true })
writeFileSync(join(outDir, 'generated.ts'), content)
