/** Auto-generated by scripts/discover-agents.ts - do not edit */

import { definition as general } from '../general/definition.js'
import { definition as crypto_analyst } from '../crypto-analyst/definition.js'

export const BUILTIN_AGENT_DEFINITIONS = [general, crypto_analyst]

export const IMPLICIT_AGENT_SERVERS: Record<string, string[]> = Object.fromEntries(
  BUILTIN_AGENT_DEFINITIONS.map((a) => [a.id, a.implicitMCPIds])
)
