/**
 * Discovers built-in MCP servers from packages/mcp-servers and packages/mcp-browser-servers.
 * Generates builtin-servers.generated.ts for @izan/mcp-client.
 */
import { readdirSync, existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const PACKAGES = join(ROOT, '..')
const MCP_SERVERS_ROOT = join(PACKAGES, 'mcp-servers')
const MCP_BROWSER_SERVERS_ROOT = join(PACKAGES, 'mcp-browser-servers')

interface ServerMetadata {
  id: string
  name: string
  description: string
  category: string
}

// ─── Backend (packages/mcp-servers) ─────────────────────────────────────────

const backendServers: ServerMetadata[] = []

if (existsSync(MCP_SERVERS_ROOT)) {
  const entries = readdirSync(MCP_SERVERS_ROOT, { withFileTypes: true })
  const serverDirs = entries
    .filter((e) => e.isDirectory() && e.name !== 'shared' && e.name !== 'integration')
    .filter((e) => existsSync(join(MCP_SERVERS_ROOT, e.name, 'src', 'index.ts')))
    .filter((e) => existsSync(join(MCP_SERVERS_ROOT, e.name, 'config.json')))
    .map((e) => e.name)
    .sort()

  for (const dir of serverDirs) {
    const configPath = join(MCP_SERVERS_ROOT, dir, 'config.json')
    const contents = readFileSync(configPath, 'utf-8')
    const config = JSON.parse(contents) as ServerMetadata
    if (config.id && config.name && config.description && config.category) {
      backendServers.push(config)
    }
  }
}

// ─── Client (packages/mcp-browser-servers) ────────────────────────────────────

const clientServers: Array<ServerMetadata & { url: string }> = []

if (existsSync(MCP_BROWSER_SERVERS_ROOT)) {
  const entries = readdirSync(MCP_BROWSER_SERVERS_ROOT, { withFileTypes: true })
  const serverDirs = entries
    .filter((e) => e.isDirectory() && e.name !== 'integration')
    .filter((e) => existsSync(join(MCP_BROWSER_SERVERS_ROOT, e.name, 'index.ts')))
    .filter((e) => existsSync(join(MCP_BROWSER_SERVERS_ROOT, e.name, 'config.json')))
    .map((e) => e.name)
    .sort()

  for (const dir of serverDirs) {
    const configPath = join(MCP_BROWSER_SERVERS_ROOT, dir, 'config.json')
    const contents = readFileSync(configPath, 'utf-8')
    const config = JSON.parse(contents) as ServerMetadata
    if (config.id && config.name && config.description && config.category) {
      clientServers.push({
        ...config,
        url: `tab://izan-${dir}`,
      })
    }
  }
}

const backendJson = JSON.stringify(
  backendServers.map((s) => ({
    id: s.id,
    name: s.name,
    description: s.description,
    category: s.category,
    urlType: 'backend',
  })),
  null,
  2,
)

const clientJson = JSON.stringify(
  clientServers.map((s) => ({
    id: s.id,
    name: s.name,
    description: s.description,
    category: s.category,
    urlType: 'client',
    url: s.url,
  })),
  null,
  2,
)

const finalOutput = `/** Auto-generated by scripts/discover-builtin-servers.ts - do not edit */

import type { ServerCategory } from './types.js'

export interface BuiltinServerMetadata {
  id: string
  name: string
  description: string
  category: ServerCategory
  urlType: 'backend' | 'client'
  url?: string
}

/** Backend MCP servers (URL resolved at runtime from MCP base) */
export const BUILTIN_BACKEND_SERVERS: BuiltinServerMetadata[] = ${backendJson}

/** Client-side MCP servers (fixed URLs, TabServerTransport) */
export const BUILTIN_CLIENT_SERVERS: BuiltinServerMetadata[] = ${clientJson}

/** @deprecated Use BUILTIN_CLIENT_SERVERS instead */
export const BUILTIN_CLIENT_SERVER: BuiltinServerMetadata = BUILTIN_CLIENT_SERVERS[0]

/** All built-in server metadata (for iteration) */
export const BUILTIN_MCP_SERVER_METADATA: BuiltinServerMetadata[] = [
  ...BUILTIN_BACKEND_SERVERS,
  ...BUILTIN_CLIENT_SERVERS,
]
`

const outPath = join(ROOT, 'src', 'builtin-servers.generated.ts')
mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, finalOutput, 'utf-8')
console.log(`[discover-builtin-servers] Wrote ${outPath} (${backendServers.length} backend + ${clientServers.length} client)`)
