/**
 * Discovers built-in MCP servers from packages/mcp-servers and packages/mcp-browser-servers.
 * Generates builtin-servers.generated.ts for @izan/mcp-client.
 */
import { readdirSync, existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const MCP_SERVERS_ROOT = join(ROOT, '..', 'mcp-servers')

interface ServerMetadata {
  id: string
  name: string
  description: string
  category: string
}

const backendServers: ServerMetadata[] = []

if (existsSync(MCP_SERVERS_ROOT)) {
  const entries = readdirSync(MCP_SERVERS_ROOT, { withFileTypes: true })
  const serverDirs = entries
    .filter((e) => e.isDirectory() && e.name !== 'shared' && e.name !== 'integration')
    .filter((e) => existsSync(join(MCP_SERVERS_ROOT, e.name, 'src', 'index.ts')))
    .filter((e) => existsSync(join(MCP_SERVERS_ROOT, e.name, 'config.json')))
    .map((e) => e.name)
    .sort()

  for (const dir of serverDirs) {
    const configPath = join(MCP_SERVERS_ROOT, dir, 'config.json')
    const contents = readFileSync(configPath, 'utf-8')
    const config = JSON.parse(contents) as ServerMetadata
    if (config.id && config.name && config.description && config.category) {
      backendServers.push(config)
    }
  }
}

const backendJson = JSON.stringify(
  backendServers.map((s) => ({
    id: s.id,
    name: s.name,
    description: s.description,
    category: s.category,
    urlType: 'backend',
  })),
  null,
  2,
)

const finalOutput = `/** Auto-generated by scripts/discover-builtin-servers.ts - do not edit */

import type { ServerCategory } from './types.js'

export interface BuiltinServerMetadata {
  id: string
  name: string
  description: string
  category: ServerCategory
  urlType: 'backend' | 'client'
  url?: string
}

/** Backend MCP servers (URL resolved at runtime from MCP base) */
export const BUILTIN_BACKEND_SERVERS: BuiltinServerMetadata[] = ${backendJson}

/** Client-side MCP servers (fixed URLs, TabServerTransport) */
export const BUILTIN_CLIENT_SERVERS: BuiltinServerMetadata[] = [
  {
    id: 'general',
    name: 'General',
    description: 'General MCP server (get_time, random_number, uuid, calculate, generate_password)',
    category: 'general',
    urlType: 'client',
    url: 'tab://izan-general',
  },
  {
    id: 'domain-check-client',
    name: 'Domain Check (Client)',
    description: 'Fast RDAP bulk availability check. No API key. 1–15 domains.',
    category: 'custom',
    urlType: 'client',
    url: 'tab://izan-domain-check',
  },
  {
    id: 'crypto-analysis-client',
    name: 'Crypto Analysis (Client)',
    description: 'Cryptocurrency market data, technical indicators (RSI/MACD/BB/EMA/SMA/ATR/Stochastic/ADX), fundamental scores, and full coin analysis via CoinGecko v3. No API key.',
    category: 'custom',
    urlType: 'client',
    url: 'tab://izan-crypto-analysis',
  },
]

/** @deprecated Use BUILTIN_CLIENT_SERVERS instead */
export const BUILTIN_CLIENT_SERVER: BuiltinServerMetadata = BUILTIN_CLIENT_SERVERS[0]

/** All built-in server metadata (for iteration) */
export const BUILTIN_MCP_SERVER_METADATA: BuiltinServerMetadata[] = [
  ...BUILTIN_BACKEND_SERVERS,
  ...BUILTIN_CLIENT_SERVERS,
]
`

const outPath = join(ROOT, 'src', 'builtin-servers.generated.ts')
mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, finalOutput, 'utf-8')
console.log(`[discover-builtin-servers] Wrote ${outPath} (${backendServers.length} backend + 3 client)`)
