/** Auto-generated by scripts/discover-builtin-servers.ts - do not edit */

import type { ServerCategory } from './types.js'

export interface BuiltinServerMetadata {
  id: string
  name: string
  description: string
  category: ServerCategory
  urlType: 'backend' | 'client' | 'extension'
  url?: string
}

/** Backend MCP servers (URL resolved at runtime from MCP base) */
export const BUILTIN_BACKEND_SERVERS: BuiltinServerMetadata[] = []

/** Client-side MCP servers (fixed URLs, TabServerTransport) */
export const BUILTIN_CLIENT_SERVERS: BuiltinServerMetadata[] = [
  {
    "id": "crypto-analysis-client",
    "name": "Crypto Analysis (Client)",
    "description": "Cryptocurrency market data, technical indicators (RSI/MACD/BB/EMA/SMA/ATR/Stochastic/ADX), fundamental scores, and full coin analysis via CoinGecko v3. No API key.",
    "category": "custom",
    "urlType": "client",
    "url": "tab://izan-crypto-analysis"
  },
  {
    "id": "domain-check-client",
    "name": "Domain Check (Client)",
    "description": "Fast RDAP bulk availability check. No API key. 1–15 domains.",
    "category": "custom",
    "urlType": "client",
    "url": "tab://izan-domain-check"
  },
  {
    "id": "general",
    "name": "General",
    "description": "General MCP server (get_time, random_number, uuid, calculate, generate_password)",
    "category": "general",
    "urlType": "client",
    "url": "tab://izan-general"
  }
]

/** Extension MCP servers (Chrome extension, TabServerTransport when extension installed) */
export const BUILTIN_EXTENSION_SERVERS: BuiltinServerMetadata[] = [
  {
    "id": "ext-random-number",
    "name": "Random Number Generator",
    "description": "Generates random numbers with configurable range and count.",
    "category": "general",
    "urlType": "extension",
    "url": "tab://izan-ext-random-number"
  }
]

/** @deprecated Use BUILTIN_CLIENT_SERVERS instead */
export const BUILTIN_CLIENT_SERVER: BuiltinServerMetadata = BUILTIN_CLIENT_SERVERS[0]

/** All built-in server metadata (for iteration) */
export const BUILTIN_MCP_SERVER_METADATA: BuiltinServerMetadata[] = [
  ...BUILTIN_BACKEND_SERVERS,
  ...BUILTIN_CLIENT_SERVERS,
  ...BUILTIN_EXTENSION_SERVERS,
]
