/** Auto-generated by scripts/discover-builtin-servers.ts - do not edit */

import type { ServerCategory } from './types.js'

export interface BuiltinServerMetadata {
  id: string
  name: string
  description: string
  category: ServerCategory
  urlType: 'backend' | 'client'
  url?: string
}

/** Backend MCP servers (URL resolved at runtime from MCP base) */
export const BUILTIN_BACKEND_SERVERS: BuiltinServerMetadata[] = [
  {
    "id": "bing",
    "name": "Bing Search",
    "description": "Search the web using Bing",
    "category": "web_search",
    "urlType": "backend"
  },
  {
    "id": "general",
    "name": "General",
    "description": "General MCP server (get_time, random_number, uuid, calculate, generate_password)",
    "category": "general",
    "urlType": "backend"
  },
  {
    "id": "google",
    "name": "Google Search",
    "description": "Search the web using Google",
    "category": "web_search",
    "urlType": "backend"
  },
  {
    "id": "namecheap",
    "name": "Namecheap Domain",
    "description": "Check domain availability and get suggestions",
    "category": "custom",
    "urlType": "backend"
  }
]

/** Client-side MCP server (fixed URL) */
export const BUILTIN_CLIENT_SERVER: BuiltinServerMetadata = {
  id: 'domain-check-client',
  name: 'Domain Check (Client)',
  description: 'Fast RDAP bulk availability check. No API key. 1–15 domains.',
  category: 'custom',
  urlType: 'client',
  url: 'tab://izan-domain-check',
}

/** All built-in server metadata (for iteration) */
export const BUILTIN_MCP_SERVER_METADATA: BuiltinServerMetadata[] = [
  ...BUILTIN_BACKEND_SERVERS,
  BUILTIN_CLIENT_SERVER,
]
